// taboryData.js

const taboryData = [
    {rok:'2025', misto:'Ronovec', tema:'Zaklínač'},
    {rok:'2024', misto:'Ronovec', tema:'Zámořské objevy'},
    {rok:'2023', misto:'Ronovec', tema:'Staré řecké báje'},
    {rok:'2022', misto:'Ronovec', tema:'Rudolf II.'},
    {rok:'2021', misto:'Ronovec', tema:'Indiáni'},
    {rok:'2020', misto:'Ronovec', tema:'Scotland Yard'},
    {rok:'2019', misto:'Ronovec', tema:'Galaktická unie'},
    {rok:'2018', misto:'Ronovec', tema:'Staré pověsti české'},
    {rok:'2017', misto:'Ronovec', tema:'Karel IV.'},
    {rok:'2016', misto:'Záblatí u Prachatic', tema:'Amazonie – Ztracené město'},
    {rok:'2015', misto:'Záblatí u Prachatic', tema:'Egypt'},
    {rok:'2014', misto:'Záblatí u Prachatic', tema:'Tajuplný ostrov'},
    {rok:'2013', misto:'Záblatí u Prachatic', tema:'Asterix a Obelix'},
    {rok:'2012', misto:'Záblatí u Prachatic', tema:'Atlantida'},
    {rok:'2011', misto:'Záblatí u Prachatic', tema:'Husité'},
    {rok:'2010', misto:'Záblatí u Prachatic', tema:'Duna'},
    {rok:'2009', misto:'Lesná u Pacova', tema:'Afrika'},
    {rok:'2008', misto:'Lesná u Pacova', tema:'Tajemství Taranathu'},
    {rok:'2007', misto:'Lesná u Pacova', tema:'Marco Polo'},
    {rok:'2006', misto:'Lesná u Pacova', tema:'Stroj času'},
    {rok:'2005', misto:'Lesná u Pacova', tema:'Ztracený ostrov'},
    {rok:'2004', misto:'Lesná u Pacova', tema:'Mafie'},
    {rok:'2003', misto:'Lesná u Pacova', tema:'Inkové'},
    {rok:'2002', misto:'Úterský potok', tema:'Projekt Tykadlo'},
    {rok:'2001', misto:'Úterský potok', tema:'Vikingové'},
    {rok:'2000', misto:'Úterský potok', tema:'Osídlování Ameriky'},
    {rok:'1999', misto:'Úterský potok', tema:'Honba za obrazem'},
    {rok:'1998', misto:'Úterský potok', tema:'Fénície'},
    {rok:'1997', misto:'Úterský potok', tema:'Indonésie'},
    {rok:'1996', misto:'Úterský potok', tema:'Přemysl Otakar II.'},
    {rok:'1995', misto:'Úterský potok', tema:'Condor Wood Company'},
    {rok:'1994', misto:'Dolní Bečva', tema:'Loď'},
    {rok:'1993', misto:'Dolní Bečva', tema:'Čína'},
    {rok:'1992', misto:'Dolní Bečva', tema:'Plesiosaurus'},
    {rok:'1991', misto:'Dolní Bečva', tema:'Železnice přes Ameriku'},
    {rok:'1990', misto:'Dolní Bečva', tema:'Mluvicí bedna'},
    {rok:'1989', misto:'Dolní Bečva', tema:'Řecko'},
    {rok:'1988', misto:'Dolní Bečva', tema:'Jiří z Poděbrad'},
    {rok:'1987', misto:'Dolní Bečva', tema:'Indiáni'},
    {rok:'1986', misto:'Dolní Bečva', tema:'Sámova říše'},
    {rok:'1985', misto:'Heřmaničky', tema:'Velrybářská výprava'},
    {rok:'1984', misto:'Heřmaničky', tema:'Černoši'},
    {rok:'1983', misto:'Heřmaničky', tema:'Husiti'},
    {rok:'1982', misto:'Biele vody', tema:'Starověké Řecko'},
    {rok:'1981', misto:'Šluknov', tema:'Lovci mamutů'},
    {rok:'1980', misto:'Biele vody', tema:'Jeskyně'},
    {rok:'1979', misto:'Jemčina', tema:''},
    {rok:'1978', misto:'', tema:'Výstup na Matterhorn'},
    {rok:'1977', misto:'Putovní tábor', tema:''}
];
